import Image from "next/image";
import { notFound } from "next/navigation";
import QRCode from "qrcode";

import { Badge } from "@/components/ui/badge";
import { getEventGuestByShareToken, getEventWindowLabel } from "@/lib/domain/events";

export default async function PublicEventGuestPage({ params }: { params: Promise<{ shareToken: string }> }) {
  const {shareToken}=await params; const access=await getEventGuestByShareToken(shareToken); if(!access) notFound();
  const qr=access.credential_type==="qr"&&access.qr_payload?await QRCode.toDataURL(access.qr_payload,{margin:1,width:320,color:{dark:"#0c1221",light:"#ffffff"}}):null;
  return <main className="min-h-[100dvh] bg-background"><header className="bg-primary px-5 pb-8 pt-[calc(env(safe-area-inset-top)+1.5rem)] text-white"><p className="font-bold">Ventry</p><h1 className="mt-8 text-3xl font-extrabold">{access.event_name}</h1><p className="mt-2 text-white/75">Acceso personal para {access.guest_name}</p></header><div className="mx-auto max-w-xl space-y-4 px-4 py-5"><section className="rounded-2xl bg-surface p-5 text-center shadow-panel"><div className="flex justify-center"><Badge variant={access.status==="active"?"success":"outline"}>{access.status==="active"?"Acceso vigente":"Acceso no vigente"}</Badge></div><h2 className="mt-4 text-xl font-bold">{access.guest_name}</h2>{qr?<div className="mx-auto mt-5 w-fit rounded-2xl border border-border bg-white p-3"><Image alt="QR personal de acceso" height={210} src={qr} unoptimized width={210}/></div>:<div className="mt-5 rounded-2xl bg-muted p-5"><p className="text-sm text-muted-foreground">PIN personal</p><p className="mt-2 font-mono text-3xl font-bold tracking-[0.22em]">{access.credential_value}</p></div>}<dl className="mt-5 divide-y divide-border text-sm"><div className="flex justify-between gap-4 py-3"><dt className="text-muted-foreground">Vigencia</dt><dd className="text-right font-semibold">{getEventWindowLabel(access)}</dd></div><div className="flex justify-between gap-4 py-3"><dt className="text-muted-foreground">Anfitrion</dt><dd className="text-right font-semibold">{access.resident_name}</dd></div>{access.allows_companions?<div className="flex justify-between gap-4 py-3"><dt className="text-muted-foreground">Acompanantes</dt><dd className="font-semibold">Hasta {access.max_companions}</dd></div>:null}</dl></section><p className="px-3 text-center text-xs text-muted-foreground">Este enlace es personal. No muestra la lista ni datos de otras personas.</p></div></main>;
}
