"use client";

import { useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { FormMessage } from "@/components/forms/form-message";
import { ArrivalWindowFields,type ArrivalWindowEditorValue } from "@/components/invitations/arrival-window-fields";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { EventGuestRecord } from "@/lib/domain/types";

type EditableGuest=Pick<EventGuestRecord,"id"|"version"|"full_name"|"phone"|"notes"|"resident_contact_id"|"allows_companions"|"max_companions"|"attendance_status"|"removed_at">;

export function ManagedEventPanel({event}:{event:{id:string;version:number;name:string;notes:string|null;event_date:string;arrival_window_mode?:"all_day"|"from_time"|null;arrival_start?:string|null;arrival_end_date?:string|null;arrival_end?:string|null;planned_exit_date:string|null;planned_exit_time:string|null;default_allows_companions:boolean;default_max_companions:number;event_guests:EditableGuest[]}}){
 const router=useRouter();const updateKey=useRef(crypto.randomUUID());const addKey=useRef(crypto.randomUUID());const removeKeys=useRef<Record<string,string>>({});
 const[name,setName]=useState(event.name);const[notes,setNotes]=useState(event.notes??"");const[allows,setAllows]=useState(event.default_allows_companions);const[max,setMax]=useState(event.default_max_companions||1);
 const[arrival,setArrival]=useState<ArrivalWindowEditorValue>({date:event.event_date,arrivalWindowMode:event.arrival_window_mode??"all_day",arrivalStart:event.arrival_start??null,arrivalEndDate:event.arrival_end_date??null,arrivalEnd:event.arrival_end??null,plannedExitDate:event.planned_exit_date,plannedExitTime:event.planned_exit_time});
 const[newName,setNewName]=useState("");const[newPhone,setNewPhone]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState<{text:string;error?:boolean}|null>(null);
 async function request(url:string,method:string,body:object){if(busy)return;setBusy(true);setMessage(null);try{const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}))as{error?:string};if(!response.ok){setMessage({text:payload.error??"No fue posible completar la operación.",error:true});return;}setMessage({text:"Cambios guardados."});router.refresh();}catch{setMessage({text:"No pudimos conectar. Revisa tu conexión e inténtalo de nuevo.",error:true});}finally{setBusy(false);}}
 return <div className="min-w-0 space-y-3">
  <details className="rounded-2xl border border-border bg-surface px-4"><summary className="flex min-h-14 cursor-pointer list-none items-center font-bold">Editar evento</summary><form className="min-w-0 space-y-5 border-t border-border py-4" onSubmit={(e)=>{e.preventDefault();request(`/api/events/${event.id}`,"PUT",{expectedVersion:event.version,idempotencyKey:updateKey.current,name,notes:notes||null,eventDate:arrival.date,arrivalWindowMode:arrival.arrivalWindowMode,arrivalStart:arrival.arrivalStart,arrivalEndDate:arrival.arrivalEndDate,arrivalEnd:arrival.arrivalEnd,plannedExitDate:arrival.plannedExitDate,plannedExitTime:arrival.plannedExitTime,defaultAllowsCompanions:allows,defaultMaxCompanions:allows?max:0});}}><div className="space-y-2"><Label htmlFor={`event-name-${event.id}`}>Nombre</Label><Input id={`event-name-${event.id}`} required value={name} onChange={(e)=>setName(e.target.value)}/></div><ArrivalWindowFields idPrefix={`event-edit-${event.id}`} value={arrival} onChange={(field,value)=>setArrival((current)=>({...current,[field]:value}))}/><CompanionFields allows={allows} id={`event-default-${event.id}`} max={max} onAllows={setAllows} onMax={setMax}/><div className="space-y-2"><Label htmlFor={`event-notes-${event.id}`}>Notas</Label><Textarea id={`event-notes-${event.id}`} value={notes} onChange={(e)=>setNotes(e.target.value)}/></div><Button className="w-full sm:w-auto" disabled={busy}>Guardar evento</Button></form></details>
  <details className="rounded-2xl border border-border bg-surface px-4"><summary className="flex min-h-14 cursor-pointer list-none items-center font-bold">Agregar invitado</summary><form className="space-y-4 border-t border-border py-4" onSubmit={(e)=>{e.preventDefault();request(`/api/events/${event.id}/guests`,"POST",{expectedVersion:event.version,idempotencyKey:addKey.current,guests:[{fullName:newName,phone:newPhone||null,notes:null,residentContactId:null,allowsCompanions:allows,maxCompanions:allows?max:0}]});}}><p className="text-sm text-muted-foreground">Se creará una credencial individual usando la configuración predeterminada actual.</p><div className="space-y-2"><Label htmlFor={`event-new-name-${event.id}`}>Nombre</Label><Input id={`event-new-name-${event.id}`} required value={newName} onChange={(e)=>setNewName(e.target.value)}/></div><div className="space-y-2"><Label htmlFor={`event-new-phone-${event.id}`}>Teléfono</Label><Input id={`event-new-phone-${event.id}`} inputMode="tel" value={newPhone} onChange={(e)=>setNewPhone(e.target.value)}/></div><Button className="w-full sm:w-auto" disabled={busy}>Agregar y crear credencial</Button></form></details>
  <details className="rounded-2xl border border-border bg-surface px-4"><summary className="flex min-h-14 cursor-pointer list-none items-center font-bold">Editar invitados</summary><div className="space-y-3 border-t border-border py-4">{event.event_guests.filter((guest)=>!guest.removed_at).map((guest)=><GuestEditor busy={busy} eventId={event.id} eventVersion={event.version} guest={guest} key={guest.id} onRequest={request} removeKey={()=>removeKeys.current[guest.id]??=(crypto.randomUUID())}/>)}</div></details>
  <FormMessage message={message?.text??null} variant={message?.error?"error":"success"}/>
 </div>;
}

function CompanionFields({allows,id,max,onAllows,onMax}:{allows:boolean;id:string;max:number;onAllows:(value:boolean)=>void;onMax:(value:number)=>void}){return <fieldset className="space-y-3"><legend className="font-semibold">Acompañantes</legend><label className="flex min-h-11 items-center gap-3"><input checked={allows} className="h-5 w-5" onChange={(e)=>onAllows(e.target.checked)} type="checkbox"/>Permitir acompañantes</label>{allows?<div className="space-y-2"><Label htmlFor={`${id}-max`}>Máximo</Label><select className="h-12 w-full rounded-md border border-border bg-surface px-3" id={`${id}-max`} value={max} onChange={(e)=>onMax(Number(e.target.value))}>{[1,2,3,4,5].map((value)=><option key={value} value={value}>{value} acompañante{value>1?"s":""}</option>)}</select></div>:null}</fieldset>}

function GuestEditor({busy,eventId,eventVersion,guest,onRequest,removeKey}:{busy:boolean;eventId:string;eventVersion:number;guest:EditableGuest;onRequest:(url:string,method:string,body:object)=>void;removeKey:()=>string}){const key=useRef(crypto.randomUUID());const[name,setName]=useState(guest.full_name);const[phone,setPhone]=useState(guest.phone??"");const[contactId,setContactId]=useState(guest.resident_contact_id);const[notes,setNotes]=useState(guest.notes??"");const[allows,setAllows]=useState(guest.allows_companions);const[max,setMax]=useState(guest.max_companions||1);const editable=guest.attendance_status==="pending";return <details className="min-w-0 rounded-xl border border-border px-3"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between gap-3"><span className="min-w-0 break-words font-semibold">{guest.full_name}</span><span className="shrink-0 text-xs text-muted-foreground">{guest.attendance_status}</span></summary><form className="space-y-4 border-t border-border py-4" onSubmit={(e)=>{e.preventDefault();onRequest(`/api/events/${eventId}/guests/${guest.id}`,"PUT",{expectedVersion:eventVersion,expectedGuestVersion:guest.version,idempotencyKey:key.current,fullName:name,phone:phone||null,notes:notes||null,residentContactId:contactId,allowsCompanions:allows,maxCompanions:allows?max:0});}}><p className="text-sm text-muted-foreground">Cambiar identidad invalida la credencial anterior y genera una nueva.</p><Input aria-label="Nombre del invitado" disabled={!editable} value={name} onChange={(e)=>{setName(e.target.value);setContactId(null);}}/><Input aria-label="Teléfono del invitado" disabled={!editable} inputMode="tel" value={phone} onChange={(e)=>{setPhone(e.target.value);setContactId(null);}}/><Textarea aria-label="Notas del invitado" disabled={!editable} value={notes} onChange={(e)=>setNotes(e.target.value)}/>{editable?<CompanionFields allows={allows} id={`guest-${guest.id}`} max={max} onAllows={setAllows} onMax={setMax}/>:null}{editable?<div className="flex flex-col gap-2 sm:flex-row"><Button disabled={busy}>Guardar invitado</Button><Button disabled={busy} onClick={()=>{if(window.confirm(`¿Retirar a ${guest.full_name}? Su credencial dejará de funcionar.`))onRequest(`/api/events/${eventId}/guests/${guest.id}`,"DELETE",{expectedVersion:eventVersion,idempotencyKey:removeKey(),reason:null});}} type="button" variant="outline">Retirar</Button></div>:<p className="text-sm text-muted-foreground">Los invitados con movimientos ya no pueden editarse ni retirarse.</p>}</form></details>}
