"use client";

import { useRef,useState } from "react";
import { useRouter } from "next/navigation";
import { FormMessage } from "@/components/forms/form-message";
import { ArrivalWindowFields,type ArrivalWindowEditorValue } from "@/components/invitations/arrival-window-fields";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { InvitationAccessType } from "@/lib/domain/types";

export function ManagedGroupPanel({group}:{group:{id:string;version:number;access_type:InvitationAccessType;notes:string|null;visit_date:string;arrival_window_mode?:"all_day"|"from_time"|null;arrival_start?:string|null;arrival_end_date?:string|null;arrival_end?:string|null;planned_exit_date?:string|null;planned_exit_time?:string|null;invitations:Array<{id:string;visitor_name:string|null;visitor_phone:string|null;status:string;removed_at:string|null}>}}){
 const router=useRouter();const updateKey=useRef(crypto.randomUUID());const addKey=useRef(crypto.randomUUID());const removeKeys=useRef<Record<string,string>>({});
 const [arrival,setArrival]=useState<ArrivalWindowEditorValue>({date:group.visit_date,arrivalWindowMode:group.arrival_window_mode??"all_day",arrivalStart:group.arrival_start??null,arrivalEndDate:group.arrival_end_date??null,arrivalEnd:group.arrival_end??null,plannedExitDate:group.planned_exit_date??null,plannedExitTime:group.planned_exit_time??null});
 const [accessType,setAccessType]=useState(group.access_type);const[notes,setNotes]=useState(group.notes??"");const[name,setName]=useState("");const[phone,setPhone]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState<{text:string;error?:boolean}|null>(null);
 async function request(url:string,method:string,body:object){if(busy)return;setBusy(true);setMessage(null);try{const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({}))as{error?:string};if(!response.ok){setMessage({text:payload.error??"No fue posible completar la operación.",error:true});return;}setMessage({text:"Cambios guardados."});router.refresh();}catch{setMessage({text:"No pudimos conectar. Revisa tu conexión e inténtalo de nuevo.",error:true});}finally{setBusy(false);}}
 return <div className="min-w-0 space-y-3">
  <details className="rounded-2xl border border-border bg-surface px-4"><summary className="flex min-h-14 cursor-pointer list-none items-center font-bold">Editar datos compartidos</summary><form className="min-w-0 space-y-5 border-t border-border py-4" onSubmit={(e)=>{e.preventDefault();request(`/api/invitation-groups/${group.id}`,"PUT",{expectedVersion:group.version,idempotencyKey:updateKey.current,accessType,notes:notes||null,visitDate:arrival.date,arrivalWindowMode:arrival.arrivalWindowMode,arrivalStart:arrival.arrivalStart,arrivalEndDate:arrival.arrivalEndDate,arrivalEnd:arrival.arrivalEnd,plannedExitDate:arrival.plannedExitDate,plannedExitTime:arrival.plannedExitTime});}}><div className="space-y-2"><Label htmlFor={`group-type-${group.id}`}>Tipo de visita</Label><select className="h-12 w-full rounded-md border border-border bg-surface px-3" id={`group-type-${group.id}`} value={accessType} onChange={(e)=>setAccessType(e.target.value as InvitationAccessType)}><option value="visitor">Visita</option><option value="delivery">Entrega</option><option value="service_provider">Proveedor</option><option value="frequent_visitor">Visitante frecuente</option></select></div><ArrivalWindowFields idPrefix={`group-edit-${group.id}`} value={arrival} onChange={(field,value)=>setArrival((current)=>({...current,[field]:value}))}/><div className="space-y-2"><Label htmlFor={`group-notes-${group.id}`}>Notas</Label><Textarea id={`group-notes-${group.id}`} value={notes} onChange={(e)=>setNotes(e.target.value)}/></div><Button className="w-full sm:w-auto" disabled={busy}>Guardar datos compartidos</Button></form></details>
  <details className="rounded-2xl border border-border bg-surface px-4"><summary className="flex min-h-14 cursor-pointer list-none items-center font-bold">Agregar persona</summary><form className="space-y-4 border-t border-border py-4" onSubmit={(e)=>{e.preventDefault();request(`/api/invitation-groups/${group.id}/members`,"POST",{expectedVersion:group.version,idempotencyKey:addKey.current,visitors:[{fullName:name,phone:phone||null,residentContactId:null}]});}}><p className="text-sm text-muted-foreground">Recibirá una credencial individual nueva con el horario actual del grupo.</p><div className="space-y-2"><Label htmlFor={`group-new-name-${group.id}`}>Nombre</Label><Input id={`group-new-name-${group.id}`} required value={name} onChange={(e)=>setName(e.target.value)}/></div><div className="space-y-2"><Label htmlFor={`group-new-phone-${group.id}`}>Teléfono</Label><Input id={`group-new-phone-${group.id}`} inputMode="tel" value={phone} onChange={(e)=>setPhone(e.target.value)}/></div><Button className="w-full sm:w-auto" disabled={busy}>Agregar y crear credencial</Button></form></details>
  <details className="rounded-2xl border border-border bg-surface px-4"><summary className="flex min-h-14 cursor-pointer list-none items-center font-bold">Administrar personas</summary><div className="space-y-2 border-t border-border py-4">{group.invitations.filter((item)=>!item.removed_at).map((item)=><div className="flex min-w-0 flex-wrap items-center justify-between gap-3 rounded-xl border border-border p-3" key={item.id}><div className="min-w-0"><p className="break-words font-semibold">{item.visitor_name}</p><p className="text-sm text-muted-foreground">{item.visitor_phone||"Sin teléfono"} · {item.status}</p></div>{item.status==="active"?<Button disabled={busy} onClick={()=>{if(window.confirm(`¿Retirar a ${item.visitor_name}? Su credencial dejará de funcionar.`))request(`/api/invitation-groups/${group.id}/members/${item.id}`,"DELETE",{expectedVersion:group.version,idempotencyKey:removeKeys.current[item.id]??=(crypto.randomUUID()),reason:null});}} type="button" variant="outline">Retirar</Button>:null}</div>)}</div></details>
  <FormMessage message={message?.text??null} variant={message?.error?"error":"success"}/>
 </div>;
}
