import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, describe, expect, it, vi } from "vitest";
import { GuardUpcomingAccess } from "@/components/guards/guard-upcoming-access";

describe("GuardUpcomingAccess",()=>{afterEach(()=>vi.restoreAllMocks());
it("shows an honest empty state without fabricated accesses",()=>{render(<GuardUpcomingAccess initial={{items:[],total:0,page:1,pageSize:3}}/>);expect(screen.getByText("Eventos de hoy")).toBeInTheDocument();expect(screen.getByText("No hay eventos ni grupos activos o proximos.")).toBeInTheDocument();});
it("renders event and group metrics from the server result",()=>{render(<GuardUpcomingAccess initial={{total:1,page:1,pageSize:3,items:[{kind:"event",id:"event-1",label:"Asamblea",access_date:"2026-08-21",window_start:"20:00",window_end_date:"2026-08-21",window_end:"22:00",host_name:"Residente real",unit_identifier:"4-B",unit_building:null,pending_count:4,inside_count:1,exited_count:2,start_at:"2026-08-21T20:00:00Z",end_at:"2026-08-21T22:00:00Z",timing_status:"next"}]}}/>);expect(screen.getByText("Asamblea")).toBeInTheDocument();expect(screen.getByText("4 pendientes · 1 dentro · 2 salieron")).toBeInTheDocument();expect(screen.getByText("Proximo")).toBeInTheDocument();expect(screen.getByRole("link",{name:"Ver detalle"})).toHaveAttribute("href","/app/events/event-1");});
it("preserves the chosen temporal filter when loading the operational panel",async()=>{const item={kind:"event" as const,id:"event-1",label:"Asamblea",access_date:"2026-08-21",window_start:"20:00",window_end_date:"2026-08-21",window_end:"22:00",host_name:"Residente real",unit_identifier:"4-B",unit_building:null,pending_count:4,inside_count:1,exited_count:2,start_at:"2026-08-21T20:00:00Z",end_at:"2026-08-21T22:00:00Z",timing_status:"active" as const};const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({items:[item],total:1,page:1,pageSize:10}),{status:200,headers:{"Content-Type":"application/json"}}));vi.stubGlobal("fetch",fetchMock);const user=userEvent.setup();render(<GuardUpcomingAccess initial={{total:4,page:1,pageSize:3,items:[item]}}/>);await user.click(screen.getByRole("button",{name:"Ver todos (4)"}));await user.selectOptions(screen.getByLabelText("Estado temporal"),"active");await user.click(screen.getByRole("button",{name:"Aplicar"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledWith(expect.stringContaining("status=active"),expect.anything()));},10_000);});
