"use client";

import { CalendarClock, RefreshCw, Search, X } from "lucide-react";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import type { GuardUpcomingAccessItem } from "@/lib/domain/guards";

type Result={items:GuardUpcomingAccessItem[];total:number;page:number;pageSize:number};
function Row({item}:{item:GuardUpcomingAccessItem}){return <article className="rounded-2xl border border-border bg-surface p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-primary">{item.kind==="event"?"Evento":"Grupo"}</p><h3 className="mt-1 font-bold">{item.label}</h3><p className="mt-1 text-sm text-muted-foreground">{item.window_start.slice(0,5)} · {item.host_name} · {item.unit_identifier??"Sin unidad"}</p></div><Badge variant={item.timing_status==="active"?"success":"outline"}>{item.timing_status==="active"?"Activo":"Proximo"}</Badge></div><p className="mt-3 text-xs text-muted-foreground">{item.pending_count} pendientes · {item.inside_count} dentro · {item.exited_count} salieron</p><div className="mt-2 flex flex-wrap gap-4"><Link className="inline-flex min-h-11 items-center font-bold text-primary" href={item.kind==="event"?`/app/events/${item.id}`:`/app/invitation-groups/${item.id}`}>Ver detalle</Link><Link className="inline-flex min-h-11 items-center font-bold text-primary" href="/app/guards?action=pin#guard-validation">Validar acceso</Link></div></article>}
export function GuardUpcomingAccess({initial}:{initial:Result}){
 const [data,setData]=useState(initial); const [open,setOpen]=useState(false); const [query,setQuery]=useState(""); const [status,setStatus]=useState("all"); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
 const load=useCallback(async(page=1,q=query,s=status)=>{setLoading(true);setError(null);try{const params=new URLSearchParams({page:String(page),pageSize:open?"10":"3",q,status:s});const response=await fetch(`/api/guards/upcoming-access?${params}`,{cache:"no-store"});const payload=await response.json() as Result&{error?:string};if(!response.ok)throw new Error(payload.error);setData(payload);}catch{setError("No pudimos actualizar los accesos.");}finally{setLoading(false)}},[open,query,status]);
 useEffect(()=>{const timer=window.setInterval(()=>void load(1),60000);const focus=()=>void load(1);window.addEventListener("focus",focus);return()=>{window.clearInterval(timer);window.removeEventListener("focus",focus)}},[load]);
 return <section className="mb-5 rounded-2xl border border-primary/20 bg-secondary/35 p-4"><div className="flex items-center justify-between gap-3"><div><p className="inline-flex items-center gap-2 font-bold"><CalendarClock className="h-5 w-5 text-primary"/>Eventos de hoy</p><p className="mt-1 text-sm text-muted-foreground">Activos ahora y proximas 6 horas.</p></div><Button aria-label="Actualizar accesos" disabled={loading} onClick={()=>void load(1)} size="icon" variant="ghost"><RefreshCw className={loading?"h-4 w-4 animate-spin":"h-4 w-4"}/></Button></div>{error?<p className="mt-3 text-sm text-danger" role="alert">{error}</p>:null}<div className="mt-4 grid gap-3 lg:grid-cols-3">{data.items.slice(0,3).map(item=><Row item={item} key={`${item.kind}-${item.id}`}/>)}</div>{!data.items.length?<p className="mt-4 rounded-xl border border-dashed border-border p-4 text-sm text-muted-foreground">No hay eventos ni grupos activos o proximos.</p>:null}{data.total>3?<button className="mt-3 min-h-11 font-bold text-primary" onClick={()=>{setOpen(true);setTimeout(()=>void load(1,query,status),0)}} type="button">Ver todos ({data.total})</button>:null}
 {open?<div aria-modal="true" className="fixed inset-0 z-[80] bg-black/40" role="dialog"><div className="absolute inset-x-0 bottom-0 max-h-[90dvh] overflow-y-auto rounded-t-3xl bg-background p-4 pb-[calc(env(safe-area-inset-bottom)+1rem)] md:inset-y-0 md:left-auto md:right-0 md:w-[32rem] md:max-h-none md:rounded-none"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Accesos de hoy</h2><Button aria-label="Cerrar" onClick={()=>setOpen(false)} size="icon" variant="ghost"><X className="h-5 w-5"/></Button></div><div className="mt-4 grid grid-cols-[1fr_9rem] gap-2"><label className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input aria-label="Buscar acceso" className="h-12 w-full rounded-xl border border-border bg-surface pl-10 pr-3 text-base" value={query} onChange={e=>setQuery(e.target.value)} /></label><select aria-label="Estado temporal" className="h-12 rounded-xl border border-border bg-surface px-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos</option><option value="active">Activos</option><option value="next">Proximos</option></select></div><Button className="mt-2 w-full" onClick={()=>void load(1)} type="button">Aplicar</Button><div className="mt-4 space-y-3">{data.items.map(item=><Row item={item} key={`${item.kind}-${item.id}`}/>)}</div><nav aria-label="Paginacion de accesos" className="mt-4 flex items-center justify-between"><Button disabled={data.page<=1||loading} onClick={()=>void load(data.page-1)} variant="outline">Anterior</Button><span className="text-sm">Pagina {data.page}</span><Button disabled={data.page*data.pageSize>=data.total||loading} onClick={()=>void load(data.page+1)} variant="outline">Siguiente</Button></nav></div></div>:null}</section>;
}
